@props(['selected'=>false,'label'])
@php
    $countries = [
        ["alpha-2"=>"AF","dialling-code"=>"93","flag"=>"&#x1F1E6&#x1F1EB","name"=>"Afghanistan"],
        ["alpha-2"=>"AL","dialling-code"=>"355","flag"=>"&#x1F1E6&#x1F1FD","name"=>"Albania"],
        ["alpha-2"=>"DZ","dialling-code"=>"213","flag"=>"&#x1F1E9&#x1F1FF","name"=>"Algeria"],
        ["alpha-2"=>"AD","dialling-code"=>"376","flag"=>"&#x1F1E6&#x1F1E9","name"=>"Andorra"],
        ["alpha-2"=>"AO","dialling-code"=>"244","flag"=>"&#x1F1E6&#x1F1F4","name"=>"Angola"],
        ["alpha-2"=>"AI","dialling-code"=>"1264","flag"=>"&#x1F1E6&#x1F1EE","name"=>"Anguilla"],
        ["alpha-2"=>"AG","dialling-code"=>"1268","flag"=>"&#x1F1E6&#x1F1EC","name"=>"Antigua &amp; Barbuda"],
        ["alpha-2"=>"AR","dialling-code"=>"54","flag"=>"&#x1F1E6&#x1F1F7","name"=>"Argentina"],
        ["alpha-2"=>"AM","dialling-code"=>"374","flag"=>"&#x1F1E6&#x1F1F2","name"=>"Armenia"],
        ["alpha-2"=>"AW","dialling-code"=>"297","flag"=>"&#x1F1E6&#x1F1FC","name"=>"Aruba"],
        ["alpha-2"=>"AC","dialling-code"=>"247","flag"=>"&#x1F1E6&#x1F1E8","name"=>"Ascension Island"],
        ["alpha-2"=>"AU","dialling-code"=>"61","flag"=>"&#x1F1E6&#x1F1FA","name"=>"Australia"],
        ["alpha-2"=>"AT","dialling-code"=>"43","flag"=>"&#x1F1E6&#x1F1F9","name"=>"Austria"],
        ["alpha-2"=>"AZ","dialling-code"=>"994","flag"=>"&#x1F1E6&#x1F1FF","name"=>"Azerbaijan"],
        ["alpha-2"=>"BS","dialling-code"=>"1242","flag"=>"&#x1F1E7&#x1F1F8","name"=>"Bahamas"],
        ["alpha-2"=>"BH","dialling-code"=>"973","flag"=>"&#x1F1E7&#x1F1ED","name"=>"Bahrain"],
        ["alpha-2"=>"BD","dialling-code"=>"880","flag"=>"&#x1F1E7&#x1F1E9","name"=>"Bangladesh"],
        ["alpha-2"=>"BB","dialling-code"=>"1246","flag"=>"&#x1F1E7&#x1F1E7","name"=>"Barbados"],
        ["alpha-2"=>"BY","dialling-code"=>"375","flag"=>"&#x1F1E7&#x1F1FE","name"=>"Belarus"],
        ["alpha-2"=>"BE","dialling-code"=>"32","flag"=>"&#x1F1E7&#x1F1EA","name"=>"Belgium"],
        ["alpha-2"=>"BZ","dialling-code"=>"501","flag"=>"&#x1F1E7&#x1F1FF","name"=>"Belize"],
        ["alpha-2"=>"BJ","dialling-code"=>"229","flag"=>"&#x1F1E7&#x1F1EF","name"=>"Benin"],
        ["alpha-2"=>"BM","dialling-code"=>"1441","flag"=>"&#x1F1E7&#x1F1F2","name"=>"Bermuda"],
        ["alpha-2"=>"BT","dialling-code"=>"975","flag"=>"&#x1F1E7&#x1F1F9","name"=>"Bhutan"],
        ["alpha-2"=>"BO","dialling-code"=>"591","flag"=>"&#x1F1E7&#x1F1F4","name"=>"Bolivia"],
        ["alpha-2"=>"BQ","dialling-code"=>"599","flag"=>"&#x1F1E7&#x1F1F6","name"=>"Bonaire, Saba and Sint Eustatius"],
        ["alpha-2"=>"BA","dialling-code"=>"387","flag"=>"&#x1F1E7&#x1F1E6","name"=>"Bosnia Herzegovina"],
        ["alpha-2"=>"BW","dialling-code"=>"267","flag"=>"&#x1F1E7&#x1F1FC","name"=>"Botswana"],
        ["alpha-2"=>"BR","dialling-code"=>"55","flag"=>"&#x1F1E7&#x1F1F7","name"=>"Brazil"],
        ["alpha-2"=>"IO","dialling-code"=>"246","flag"=>"&#x1F1EE&#x1F1F4","name"=>"British Indian Ocean Territory"],
        ["alpha-2"=>"BN","dialling-code"=>"673","flag"=>"&#x1F1E7&#x1F1F3","name"=>"Brunei"],
        ["alpha-2"=>"BG","dialling-code"=>"359","flag"=>"&#x1F1E7&#x1F1EC","name"=>"Bulgaria"],
        ["alpha-2"=>"BF","dialling-code"=>"226","flag"=>"&#x1F1E7&#x1F1EB","name"=>"Burkina Faso"],
        ["alpha-2"=>"BI","dialling-code"=>"257","flag"=>"&#x1F1E7&#x1F1EE","name"=>"Burundi"],
        ["alpha-2"=>"KH","dialling-code"=>"855","flag"=>"&#x1F1F0&#x1F1ED","name"=>"Cambodia"],
        ["alpha-2"=>"CM","dialling-code"=>"237","flag"=>"&#x1F1E8&#x1F1F2","name"=>"Cameroon"],
        ["alpha-2"=>"CA","dialling-code"=>"1","flag"=>"&#x1F1E8&#x1F1E6","name"=>"Canada"],
        ["alpha-2"=>"CV","dialling-code"=>"238","flag"=>"&#x1F1E8&#x1F1FB","name"=>"Cape Verde Islands"],
        ["alpha-2"=>"KY","dialling-code"=>"1345","flag"=>"&#x1F1F0&#x1F1FE","name"=>"Cayman Islands"],
        ["alpha-2"=>"CF","dialling-code"=>"236","flag"=>"&#x1F1E8&#x1F1EB","name"=>"Central African Republic"],
        ["alpha-2"=>"TD","dialling-code"=>"235","flag"=>"&#x1F1F9&#x1F1E9","name"=>"Chad"],
        ["alpha-2"=>"CL","dialling-code"=>"56","flag"=>"&#x1F1E8&#x1F1F1","name"=>"Chile"],
        ["alpha-2"=>"CN","dialling-code"=>"86","flag"=>"&#x1F1E8&#x1F1F3","name"=>"China"],
        ["alpha-2"=>"CO","dialling-code"=>"57","flag"=>"&#x1F1E8&#x1F1F4","name"=>"Colombia"],
        ["alpha-2"=>"KM","dialling-code"=>"269","flag"=>"&#x1F1F0&#x1F1F2","name"=>"Comoros"],
        ["alpha-2"=>"CG","dialling-code"=>"242","flag"=>"&#x1F1E8&#x1F1EC","name"=>"Congo"],
        ["alpha-2"=>"CD","dialling-code"=>"243","flag"=>"&#x1F1E8&#x1F1E9","name"=>"Congo, Democratic Republic of the"],
        ["alpha-2"=>"CK","dialling-code"=>"682","flag"=>"&#x1F1E8&#x1F1F0","name"=>"Cook Islands"],
        ["alpha-2"=>"CR","dialling-code"=>"506","flag"=>"&#x1F1E8&#x1F1F7","name"=>"Costa Rica"],
        ["alpha-2"=>"HR","dialling-code"=>"385","flag"=>"&#x1F1ED&#x1F1F7","name"=>"Croatia"],
        ["alpha-2"=>"CU","dialling-code"=>"53","flag"=>"&#x1F1E8&#x1F1FA","name"=>"Cuba"],
        ["alpha-2"=>"CW","dialling-code"=>"5999","flag"=>"&#x1F1E8&#x1F1FC","name"=>"Curaçao"],
        ["alpha-2"=>"CY","dialling-code"=>"357","flag"=>"&#x1F1E8&#x1F1FE","name"=>"Cyprus"],
        ["alpha-2"=>"CZ","dialling-code"=>"420","flag"=>"&#x1F1E8&#x1F1FF","name"=>"Czech Republic"],
        ["alpha-2"=>"DK","dialling-code"=>"45","flag"=>"&#x1F1E9&#x1F1F0","name"=>"Denmark"],
        ["alpha-2"=>"DJ","dialling-code"=>"253","flag"=>"&#x1F1E9&#x1F1EF","name"=>"Djibouti"],
        ["alpha-2"=>"DM","dialling-code"=>"1767","flag"=>"&#x1F1E9&#x1F1F2","name"=>"Dominica"],
        ["alpha-2"=>"DO","dialling-code"=>"1809","flag"=>"&#x1F1E9&#x1F1F4","name"=>"Dominican Republic"],
        ["alpha-2"=>"TL","dialling-code"=>"670","flag"=>"&#x1F1F9&#x1F1F1","name"=>"East Timor"],
        ["alpha-2"=>"EC","dialling-code"=>"593","flag"=>"&#x1F1EA&#x1F1E8","name"=>"Ecuador"],
        ["alpha-2"=>"EG","dialling-code"=>"20","flag"=>"&#x1F1EA&#x1F1EC","name"=>"Egypt"],
        ["alpha-2"=>"SV","dialling-code"=>"503","flag"=>"&#x1F1F8&#x1F1FB","name"=>"El Salvador"],
        ["alpha-2"=>"GQ","dialling-code"=>"240","flag"=>"&#x1F1EC&#x1F1F6","name"=>"Equatorial Guinea"],
        ["alpha-2"=>"ER","dialling-code"=>"291","flag"=>"&#x1F1EA&#x1F1F7","name"=>"Eritrea"],
        ["alpha-2"=>"EE","dialling-code"=>"372","flag"=>"&#x1F1EA&#x1F1EA","name"=>"Estonia"],
        ["alpha-2"=>"SZ","dialling-code"=>"268","flag"=>"&#x1F1F8&#x1F1FF","name"=>"Eswatini"],
        ["alpha-2"=>"ET","dialling-code"=>"251","flag"=>"&#x1F1EA&#x1F1F9","name"=>"Ethiopia"],
        ["alpha-2"=>"FK","dialling-code"=>"500","flag"=>"&#x1F1EB&#x1F1F0","name"=>"Falkland Islands"],
        ["alpha-2"=>"FO","dialling-code"=>"298","flag"=>"&#x1F1EB&#x1F1F4","name"=>"Faroe Islands"],
        ["alpha-2"=>"FJ","dialling-code"=>"679","flag"=>"&#x1F1EB&#x1F1EF","name"=>"Fiji"],
        ["alpha-2"=>"FI","dialling-code"=>"358","flag"=>"&#x1F1EB&#x1F1EE","name"=>"Finland"],
        ["alpha-2"=>"FR","dialling-code"=>"33","flag"=>"&#x1F1EB&#x1F1F7","name"=>"France"],
        ["alpha-2"=>"GF","dialling-code"=>"594","flag"=>"&#x1F1EC&#x1F1EB","name"=>"French Guiana"],
        ["alpha-2"=>"PF","dialling-code"=>"689","flag"=>"&#x1F1F5&#x1F1EB","name"=>"French Polynesia"],
        ["alpha-2"=>"GA","dialling-code"=>"241","flag"=>"&#x1F1EC&#x1F1E6","name"=>"Gabon"],
        ["alpha-2"=>"GM","dialling-code"=>"220","flag"=>"&#x1F1EC&#x1F1F2","name"=>"Gambia"],
        ["alpha-2"=>"GE","dialling-code"=>"995","flag"=>"&#x1F1EC&#x1F1EA","name"=>"Georgia"],
        ["alpha-2"=>"DE","dialling-code"=>"49","flag"=>"&#x1F1E9&#x1F1EA","name"=>"Germany"],
        ["alpha-2"=>"GH","dialling-code"=>"233","flag"=>"&#x1F1EC&#x1F1ED","name"=>"Ghana"],
        ["alpha-2"=>"GI","dialling-code"=>"350","flag"=>"&#x1F1EC&#x1F1EE","name"=>"Gibraltar"],
        ["alpha-2"=>"GR","dialling-code"=>"30","flag"=>"&#x1F1EC&#x1F1F7","name"=>"Greece"],
        ["alpha-2"=>"GL","dialling-code"=>"299","flag"=>"&#x1F1EC&#x1F1F1","name"=>"Greenland"],
        ["alpha-2"=>"GD","dialling-code"=>"1473","flag"=>"&#x1F1EC&#x1F1E9","name"=>"Grenada"],
        ["alpha-2"=>"GP","dialling-code"=>"590","flag"=>"&#x1F1EC&#x1F1F5","name"=>"Guadeloupe"],
        ["alpha-2"=>"GU","dialling-code"=>"1671","flag"=>"&#x1F1EC&#x1F1FA","name"=>"Guam"],
        ["alpha-2"=>"GT","dialling-code"=>"502","flag"=>"&#x1F1EC&#x1F1F9","name"=>"Guatemala"],
        ["alpha-2"=>"GN","dialling-code"=>"224","flag"=>"&#x1F1EC&#x1F1F3","name"=>"Guinea"],
        ["alpha-2"=>"GW","dialling-code"=>"245","flag"=>"&#x1F1EC&#x1F1FC","name"=>"Guinea - Bissau"],
        ["alpha-2"=>"GY","dialling-code"=>"592","flag"=>"&#x1F1EC&#x1F1FE","name"=>"Guyana"],
        ["alpha-2"=>"HT","dialling-code"=>"509","flag"=>"&#x1F1ED&#x1F1F9","name"=>"Haiti"],
        ["alpha-2"=>"HN","dialling-code"=>"504","flag"=>"&#x1F1ED&#x1F1F3","name"=>"Honduras"],
        ["alpha-2"=>"HK","dialling-code"=>"852","flag"=>"&#x1F1ED&#x1F1F0","name"=>"Hong Kong"],
        ["alpha-2"=>"HU","dialling-code"=>"36","flag"=>"&#x1F1ED&#x1F1FA","name"=>"Hungary"],
        ["alpha-2"=>"IS","dialling-code"=>"354","flag"=>"&#x1F1EE&#x1F1F8","name"=>"Iceland"],
        ["alpha-2"=>"IN","dialling-code"=>"91","flag"=>"&#x1F1EE&#x1F1F3","name"=>"India"],
        ["alpha-2"=>"ID","dialling-code"=>"62","flag"=>"&#x1F1EE&#x1F1E9","name"=>"Indonesia"],
        ["alpha-2"=>"IR","dialling-code"=>"98","flag"=>"&#x1F1EE&#x1F1F7","name"=>"Iran"],
        ["alpha-2"=>"IQ","dialling-code"=>"964","flag"=>"&#x1F1EE&#x1F1F6","name"=>"Iraq"],
        ["alpha-2"=>"IE","dialling-code"=>"353","flag"=>"&#x1F1EE&#x1F1EA","name"=>"Ireland"],
        ["alpha-2"=>"IL","dialling-code"=>"972","flag"=>"&#x1F1EE&#x1F1F1","name"=>"Israel"],
        ["alpha-2"=>"IT","dialling-code"=>"39","flag"=>"&#x1F1EE&#x1F1F9","name"=>"Italy"],
        ["alpha-2"=>"CI","dialling-code"=>"225","flag"=>"&#x1F1E8&#x1F1EE","name"=>"Ivory Coast"],
        ["alpha-2"=>"JM","dialling-code"=>"1876","flag"=>"&#x1F1EF&#x1F1F2","name"=>"Jamaica"],
        ["alpha-2"=>"JP","dialling-code"=>"81","flag"=>"&#x1F1EF&#x1F1F5","name"=>"Japan"],
        ["alpha-2"=>"JO","dialling-code"=>"962","flag"=>"&#x1F1EF&#x1F1F4","name"=>"Jordan"],
        ["alpha-2"=>"KZ","dialling-code"=>"7","flag"=>"&#x1F1F0&#x1F1FF","name"=>"Kazakhstan"],
        ["alpha-2"=>"KE","dialling-code"=>"254","flag"=>"&#x1F1F0&#x1F1EA","name"=>"Kenya"],
        ["alpha-2"=>"KI","dialling-code"=>"686","flag"=>"&#x1F1F0&#x1F1EE","name"=>"Kiribati"],
        ["alpha-2"=>"KP","dialling-code"=>"850","flag"=>"&#x1F1F0&#x1F1F5","name"=>"Korea, North"],
        ["alpha-2"=>"KR","dialling-code"=>"82","flag"=>"&#x1F1F0&#x1F1F7","name"=>"Korea, South"],
        ["alpha-2"=>"XK","dialling-code"=>"383","flag"=>"&#x1F1FD&#x1F1F0","name"=>"Kosovo"],
        ["alpha-2"=>"KW","dialling-code"=>"965","flag"=>"&#x1F1F0&#x1F1FC","name"=>"Kuwait"],
        ["alpha-2"=>"KG","dialling-code"=>"996","flag"=>"&#x1F1F0&#x1F1EC","name"=>"Kyrgyzstan"],
        ["alpha-2"=>"LA","dialling-code"=>"856","flag"=>"&#x1F1F1&#x1F1E6","name"=>"Laos"],
        ["alpha-2"=>"LV","dialling-code"=>"371","flag"=>"&#x1F1F1&#x1F1FB","name"=>"Latvia"],
        ["alpha-2"=>"LB","dialling-code"=>"961","flag"=>"&#x1F1F1&#x1F1E7","name"=>"Lebanon"],
        ["alpha-2"=>"LS","dialling-code"=>"266","flag"=>"&#x1F1F1&#x1F1F8","name"=>"Lesotho"],
        ["alpha-2"=>"LR","dialling-code"=>"231","flag"=>"&#x1F1F1&#x1F1F7","name"=>"Liberia"],
        ["alpha-2"=>"LY","dialling-code"=>"218","flag"=>"&#x1F1F1&#x1F1FE","name"=>"Libya"],
        ["alpha-2"=>"LI","dialling-code"=>"423","flag"=>"&#x1F1F1&#x1F1EE","name"=>"Liechtenstein"],
        ["alpha-2"=>"LT","dialling-code"=>"370","flag"=>"&#x1F1F1&#x1F1F9","name"=>"Lithuania"],
        ["alpha-2"=>"LU","dialling-code"=>"352","flag"=>"&#x1F1F1&#x1F1FA","name"=>"Luxembourg"],
        ["alpha-2"=>"MO","dialling-code"=>"853","flag"=>"&#x1F1F2&#x1F1F4","name"=>"Macao"],
        ["alpha-2"=>"MK","dialling-code"=>"389","flag"=>"&#x1F1F2&#x1F1F0","name"=>"Macedonia"],
        ["alpha-2"=>"MG","dialling-code"=>"261","flag"=>"&#x1F1F2&#x1F1EC","name"=>"Madagascar"],
        ["alpha-2"=>"MW","dialling-code"=>"265","flag"=>"&#x1F1F2&#x1F1FC","name"=>"Malawi"],
        ["alpha-2"=>"MY","dialling-code"=>"60","flag"=>"&#x1F1F2&#x1F1FE","name"=>"Malaysia"],
        ["alpha-2"=>"MV","dialling-code"=>"960","flag"=>"&#x1F1F2&#x1F1FB","name"=>"Maldives"],
        ["alpha-2"=>"ML","dialling-code"=>"223","flag"=>"&#x1F1F2&#x1F1F1","name"=>"Mali"],
        ["alpha-2"=>"MT","dialling-code"=>"356","flag"=>"&#x1F1F2&#x1F1F9","name"=>"Malta"],
        ["alpha-2"=>"MH","dialling-code"=>"692","flag"=>"&#x1F1F2&#x1F1ED","name"=>"Marshall Islands"],
        ["alpha-2"=>"MQ","dialling-code"=>"596","flag"=>"&#x1F1F2&#x1F1F6","name"=>"Martinique"],
        ["alpha-2"=>"MR","dialling-code"=>"222","flag"=>"&#x1F1F2&#x1F1F7","name"=>"Mauritania"],
        ["alpha-2"=>"MU","dialling-code"=>"230","flag"=>"&#x1F1F2&#x1F1FA","name"=>"Mauritius"],
        ["alpha-2"=>"YT","dialling-code"=>"262","flag"=>"&#x1F1FE&#x1F1F9","name"=>"Mayotte"],
        ["alpha-2"=>"MX","dialling-code"=>"52","flag"=>"&#x1F1F2&#x1F1FD","name"=>"Mexico"],
        ["alpha-2"=>"FM","dialling-code"=>"691","flag"=>"&#x1F1EB&#x1F1F2","name"=>"Micronesia"],
        ["alpha-2"=>"MD","dialling-code"=>"373","flag"=>"&#x1F1F2&#x1F1E9","name"=>"Moldova"],
        ["alpha-2"=>"MC","dialling-code"=>"377","flag"=>"&#x1F1F2&#x1F1E8","name"=>"Monaco"],
        ["alpha-2"=>"MN","dialling-code"=>"976","flag"=>"&#x1F1F2&#x1F1F3","name"=>"Mongolia"],
        ["alpha-2"=>"ME","dialling-code"=>"382","flag"=>"&#x1F1F2&#x1F1EA","name"=>"Montenegro"],
        ["alpha-2"=>"MS","dialling-code"=>"1664","flag"=>"&#x1F1F2&#x1F1F8","name"=>"Montserrat"],
        ["alpha-2"=>"MA","dialling-code"=>"212","flag"=>"&#x1F1F2&#x1F1E6","name"=>"Morocco"],
        ["alpha-2"=>"MZ","dialling-code"=>"258","flag"=>"&#x1F1F2&#x1F1FF","name"=>"Mozambique"],
        ["alpha-2"=>"MN","dialling-code"=>"95","flag"=>"&#x1F1F2&#x1F1F2","name"=>"Myanmar"],
        ["alpha-2"=>"NA","dialling-code"=>"264","flag"=>"&#x1F1F3&#x1F1E6","name"=>"Namibia"],
        ["alpha-2"=>"NR","dialling-code"=>"674","flag"=>"&#x1F1F3&#x1F1F7","name"=>"Nauru"],
        ["alpha-2"=>"NP","dialling-code"=>"977","flag"=>"&#x1F1F3&#x1F1F5","name"=>"Nepal"],
        ["alpha-2"=>"NL","dialling-code"=>"31","flag"=>"&#x1F1F3&#x1F1F1","name"=>"Netherlands"],
        ["alpha-2"=>"NC","dialling-code"=>"687","flag"=>"&#x1F1F3&#x1F1E8","name"=>"New Caledonia"],
        ["alpha-2"=>"NZ","dialling-code"=>"64","flag"=>"&#x1F1F3&#x1F1FF","name"=>"New Zealand"],
        ["alpha-2"=>"NI","dialling-code"=>"505","flag"=>"&#x1F1F3&#x1F1EE","name"=>"Nicaragua"],
        ["alpha-2"=>"NE","dialling-code"=>"227","flag"=>"&#x1F1F3&#x1F1EA","name"=>"Niger"],
        ["alpha-2"=>"NG","dialling-code"=>"234","flag"=>"&#x1F1F3&#x1F1EC","name"=>"Nigeria"],
        ["alpha-2"=>"NU","dialling-code"=>"683","flag"=>"&#x1F1F3&#x1F1FA","name"=>"Niue"],
        ["alpha-2"=>"NF","dialling-code"=>"672","flag"=>"&#x1F1F3&#x1F1EB","name"=>"Norfolk Islands"],
        ["alpha-2"=>"NP","dialling-code"=>"1670","flag"=>"&#x1F1F2&#x1F1F5","name"=>"Northern Mariana Islands"],
        ["alpha-2"=>"NO","dialling-code"=>"47","flag"=>"&#x1F1F3&#x1F1F4","name"=>"Norway"],
        ["alpha-2"=>"OM","dialling-code"=>"968","flag"=>"&#x1F1F4&#x1F1F2","name"=>"Oman"],
        ["alpha-2"=>"PK","dialling-code"=>"92","flag"=>"&#x1F1F5&#x1F1F0","name"=>"Pakistan"],
        ["alpha-2"=>"PW","dialling-code"=>"680","flag"=>"&#x1F1F5&#x1F1FC","name"=>"Palau"],
        ["alpha-2"=>"PS","dialling-code"=>"970","flag"=>"&#x1F1F5&#x1F1F8","name"=>"Palestine"],
        ["alpha-2"=>"PA","dialling-code"=>"507","flag"=>"&#x1F1F5&#x1F1E6","name"=>"Panama"],
        ["alpha-2"=>"PG","dialling-code"=>"675","flag"=>"&#x1F1F5&#x1F1EC","name"=>"Papua New Guinea"],
        ["alpha-2"=>"PY","dialling-code"=>"595","flag"=>"&#x1F1F5&#x1F1FE","name"=>"Paraguay"],
        ["alpha-2"=>"PE","dialling-code"=>"51","flag"=>"&#x1F1F5&#x1F1EA","name"=>"Peru"],
        ["alpha-2"=>"PH","dialling-code"=>"63","flag"=>"&#x1F1F5&#x1F1ED","name"=>"Philippines"],
        ["alpha-2"=>"PL","dialling-code"=>"48","flag"=>"&#x1F1F5&#x1F1F1","name"=>"Poland"],
        ["alpha-2"=>"PT","dialling-code"=>"351","flag"=>"&#x1F1F5&#x1F1F9","name"=>"Portugal"],
        ["alpha-2"=>"PR","dialling-code"=>"1787","flag"=>"&#x1F1F5&#x1F1F7","name"=>"Puerto Rico"],
        ["alpha-2"=>"QA","dialling-code"=>"974","flag"=>"&#x1F1F6&#x1F1E6","name"=>"Qatar"],
        ["alpha-2"=>"RE","dialling-code"=>"262","flag"=>"&#x1F1F7&#x1F1EA","name"=>"Réunion"],
        ["alpha-2"=>"RO","dialling-code"=>"40","flag"=>"&#x1F1F7&#x1F1F4","name"=>"Romania"],
        ["alpha-2"=>"RU","dialling-code"=>"7","flag"=>"&#x1F1F7&#x1F1FA","name"=>"Russia"],
        ["alpha-2"=>"RW","dialling-code"=>"250","flag"=>"&#x1F1F7&#x1F1FC","name"=>"Rwanda"],
        ["alpha-2"=>"WS","dialling-code"=>"685","flag"=>"&#x1F1FC&#x1F1F8","name"=>"Samoa"],
        ["alpha-2"=>"SM","dialling-code"=>"378","flag"=>"&#x1F1F8&#x1F1F2","name"=>"San Marino"],
        ["alpha-2"=>"ST","dialling-code"=>"239","flag"=>"&#x1F1F8&#x1F1F9","name"=>"São Tomé &amp; Principe"],
        ["alpha-2"=>"SA","dialling-code"=>"966","flag"=>"&#x1F1F8&#x1F1E6","name"=>"Saudi Arabia"],
        ["alpha-2"=>"SN","dialling-code"=>"221","flag"=>"&#x1F1F8&#x1F1F3","name"=>"Senegal"],
        ["alpha-2"=>"CS","dialling-code"=>"381","flag"=>"&#x1F1F7&#x1F1F8","name"=>"Serbia"],
        ["alpha-2"=>"SC","dialling-code"=>"248","flag"=>"&#x1F1F8&#x1F1E8","name"=>"Seychelles"],
        ["alpha-2"=>"SL","dialling-code"=>"232","flag"=>"&#x1F1F8&#x1F1F1","name"=>"Sierra Leone"],
        ["alpha-2"=>"SG","dialling-code"=>"65","flag"=>"&#x1F1F8&#x1F1EC","name"=>"Singapore"],
        ["alpha-2"=>"SK","dialling-code"=>"421","flag"=>"&#x1F1F8&#x1F1F0","name"=>"Slovakia"],
        ["alpha-2"=>"SI","dialling-code"=>"386","flag"=>"&#x1F1F8&#x1F1EE","name"=>"Slovenia"],
        ["alpha-2"=>"SB","dialling-code"=>"677","flag"=>"&#x1F1F8&#x1F1E7","name"=>"Solomon Islands"],
        ["alpha-2"=>"SO","dialling-code"=>"252","flag"=>"&#x1F1F8&#x1F1F4","name"=>"Somalia"],
        ["alpha-2"=>"ZA","dialling-code"=>"27","flag"=>"&#x1F1FF&#x1F1E6","name"=>"South Africa"],
        ["alpha-2"=>"SS","dialling-code"=>"211","flag"=>"&#x1F1F8&#x1F1F8","name"=>"South Sudan"],
        ["alpha-2"=>"ES","dialling-code"=>"34","flag"=>"&#x1F1EA&#x1F1F8","name"=>"Spain"],
        ["alpha-2"=>"LK","dialling-code"=>"94","flag"=>"&#x1F1F1&#x1F1F0","name"=>"Sri Lanka"],
        ["alpha-2"=>"SH","dialling-code"=>"290","flag"=>"&#x1F1F8&#x1F1ED","name"=>"St. Helena"],
        ["alpha-2"=>"KN","dialling-code"=>"1869","flag"=>"&#x1F1F0&#x1F1F3","name"=>"St. Kitts and Nevis"],
        ["alpha-2"=>"SC","dialling-code"=>"1758","flag"=>"&#x1F1F1&#x1F1E8","name"=>"St. Lucia"],
        ["alpha-2"=>"PM","dialling-code"=>"508","flag"=>"&#x1F1F5&#x1F1F2","name"=>"St. Pierre and Miquelon"],
        ["alpha-2"=>"SD","dialling-code"=>"249","flag"=>"&#x1F1F8&#x1F1E9","name"=>"Sudan"],
        ["alpha-2"=>"SR","dialling-code"=>"597","flag"=>"&#x1F1F8&#x1F1F7","name"=>"Suriname"],
        ["alpha-2"=>"SE","dialling-code"=>"46","flag"=>"&#x1F1F8&#x1F1EA","name"=>"Sweden"],
        ["alpha-2"=>"CH","dialling-code"=>"41","flag"=>"&#x1F1E8&#x1F1ED","name"=>"Switzerland"],
        ["alpha-2"=>"SI","dialling-code"=>"963","flag"=>"&#x1F1F8&#x1F1FE","name"=>"Syria"],
        ["alpha-2"=>"TW","dialling-code"=>"886","flag"=>"&#x1F1F9&#x1F1FC","name"=>"Taiwan"],
        ["alpha-2"=>"TJ","dialling-code"=>"992","flag"=>"&#x1F1F9&#x1F1EF","name"=>"Tajikstan"],
        ["alpha-2"=>"TZ","dialling-code"=>"255","flag"=>"&#x1F1F9&#x1F1FF","name"=>"Tanzania"],
        ["alpha-2"=>"TH","dialling-code"=>"66","flag"=>"&#x1F1F9&#x1F1ED","name"=>"Thailand"],
        ["alpha-2"=>"TG","dialling-code"=>"228","flag"=>"&#x1F1F9&#x1F1EC","name"=>"Togo"],
        ["alpha-2"=>"TK","dialling-code"=>"690","flag"=>"&#x1F1F9&#x1F1F0","name"=>"Tokelau"],
        ["alpha-2"=>"TO","dialling-code"=>"676","flag"=>"&#x1F1F9&#x1F1F4","name"=>"Tonga"],
        ["alpha-2"=>"TT","dialling-code"=>"1868","flag"=>"&#x1F1F9&#x1F1F9","name"=>"Trinidad &amp; Tobago"],
        ["alpha-2"=>"TN","dialling-code"=>"216","flag"=>"&#x1F1F9&#x1F1F3","name"=>"Tunisia"],
        ["alpha-2"=>"TR","dialling-code"=>"90","flag"=>"&#x1F1F9&#x1F1F7","name"=>"Turkey"],
        ["alpha-2"=>"TM","dialling-code"=>"993","flag"=>"&#x1F1F9&#x1F1F2","name"=>"Turkmenistan"],
        ["alpha-2"=>"TC","dialling-code"=>"1649","flag"=>"&#x1F1F9&#x1F1E8","name"=>"Turks &amp; Caicos Islands"],
        ["alpha-2"=>"TV","dialling-code"=>"688","flag"=>"&#x1F1F9&#x1F1FB","name"=>"Tuvalu"],
        ["alpha-2"=>"UG","dialling-code"=>"256","flag"=>"&#x1F1FA&#x1F1EC","name"=>"Uganda"],
        ["alpha-2"=>"UA","dialling-code"=>"380","flag"=>"&#x1F1FA&#x1F1E6","name"=>"Ukraine"],
        ["alpha-2"=>"AE","dialling-code"=>"971","flag"=>"&#x1F1E6&#x1F1EA","name"=>"United Arab Emirates"],
        ["alpha-2"=>"GB","dialling-code"=>"44","flag"=>"&#x1F1EC&#x1F1E7","name"=>"United Kingdom"],
        ["alpha-2"=>"US","dialling-code"=>"1","flag"=>"&#x1F1FA&#x1F1F8","name"=>"United States of America"],
        ["alpha-2"=>"UY","dialling-code"=>"598","flag"=>"&#x1F1FA&#x1F1FE","name"=>"Uruguay"],
        ["alpha-2"=>"UZ","dialling-code"=>"998","flag"=>"&#x1F1FA&#x1F1FF","name"=>"Uzbekistan"],
        ["alpha-2"=>"VU","dialling-code"=>"678","flag"=>"&#x1F1FB&#x1F1FA","name"=>"Vanuatu"],
        ["alpha-2"=>"VA","dialling-code"=>"39","flag"=>"&#x1F1FB&#x1F1E6","name"=>"Vatican City"],
        ["alpha-2"=>"VE","dialling-code"=>"58","flag"=>"&#x1F1FB&#x1F1EA","name"=>"Venezuela"],
        ["alpha-2"=>"VN","dialling-code"=>"84","flag"=>"&#x1F1FB&#x1F1F3","name"=>"Vietnam"],
        ["alpha-2"=>"VG","dialling-code"=>"1284","flag"=>"&#x1F1FB&#x1F1EC","name"=>"Virgin Islands - British"],
        ["alpha-2"=>"VI","dialling-code"=>"1340","flag"=>"&#x1F1FB&#x1F1EE","name"=>"Virgin Islands - US"],
        ["alpha-2"=>"WF","dialling-code"=>"681","flag"=>"&#x1F1FC&#x1F1EB","name"=>"Wallis &amp; Futuna"],
        ["alpha-2"=>"EH","dialling-code"=>"967","flag"=>"&#x1F1EA&#x1F1ED","name"=>"Western Sahara"],
        ["alpha-2"=>"YE","dialling-code"=>"967","flag"=>"&#x1F1FE&#x1F1EA","name"=>"Yemen"],
        ["alpha-2"=>"ZM","dialling-code"=>"260","flag"=>"&#x1F1FF&#x1F1F2","name"=>"Zambia"],
        ["alpha-2"=>"ZW","dialling-code"=>"263","flag"=>"&#x1F1FF&#x1F1FC","name"=>"Zimbabwe"]
    ];
@endphp
<x-forms::input.select label="{{ $label }}" {{ $attributes }}>
    @php
        foreach ($countries as $country){
            echo "<option value=\"".$country['alpha-2']."\"";
            if($selected == $country['alpha-2']){
                echo " selected";
            }
            echo ">".$country['flag']." ".$country['name']." (+".$country['dialling-code'].")</option>";
        }
    @endphp
</x-forms::input.select>
